	<option value="-1" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 1>selected="selected"</#if>>请选择</option>
	<option status="1" value="1" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 1>selected="selected"</#if>>阿富汗</option>
    <option status="1" value="2" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 2>selected="selected"</#if>>阿尔巴尼亚</option>
    <option status="1" value="3" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 3>selected="selected"</#if>>阿尔及利亚</option>
    <option status="1" value="4" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 4>selected="selected"</#if>>安道尔共和国</option>
    <option status="1" value="5" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 5>selected="selected"</#if>>安哥拉</option>
    <option status="1" value="6" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 6>selected="selected"</#if>>安圭拉岛</option>
    <option status="1" value="7" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 7>selected="selected"</#if>>安提瓜和巴布达</option>
    <option status="1" value="8" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 8>selected="selected"</#if>>阿根廷</option>
    <option status="1" value="9" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 9>selected="selected"</#if>>亚美尼亚</option>
    <option status="1" value="10" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 10>selected="selected"</#if>>澳大利亚</option>
    <option status="1" value="11" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 11>selected="selected"</#if>>奥地利</option>
    <option status="1" value="12" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 12>selected="selected"</#if>>阿塞拜疆</option>
    <option status="1" value="13" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 13>selected="selected"</#if>>巴哈马</option>
    <option status="1" value="14" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 14>selected="selected"</#if>>巴林</option>
    <option status="1" value="15" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 15>selected="selected"</#if>>孟加拉国</option>
    <option status="1" value="16" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 16>selected="selected"</#if>>巴巴多斯</option>
    <option status="1" value="17" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 17>selected="selected"</#if>>白俄罗斯</option>
    <option status="1" value="18" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 18>selected="selected"</#if>>比利时</option>
    <option status="1" value="19" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 19>selected="selected"</#if>>伯利兹</option>
    <option status="1" value="20" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 20>selected="selected"</#if>>贝宁</option>
    <option status="1" value="21" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 21>selected="selected"</#if>>百慕大群岛</option>
    <option status="1" value="22" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 22>selected="selected"</#if>>玻利维亚</option>
    <option status="1" value="23" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 23>selected="selected"</#if>>博茨瓦纳</option>
    <option status="1" value="24" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 24>selected="selected"</#if>>巴西</option>
    <option status="1" value="25" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 25>selected="selected"</#if>>文莱</option>
    <option status="1" value="26" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 26>selected="selected"</#if>>保加利亚</option>
    <option status="1" value="27" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 27>selected="selected"</#if>>布基纳法索</option>
    <option status="1" value="28" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 28>selected="selected"</#if>>缅甸</option>
    <option status="1" value="29" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 29>selected="selected"</#if>>布隆迪</option>
    <option status="1" value="30" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 30>selected="selected"</#if>>喀麦隆</option>
    <option status="1" value="31" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 31>selected="selected"</#if>>加拿大</option>
    <option status="1" value="32" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 32>selected="selected"</#if>>中非共和国</option>
    <option status="1" value="33" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 33>selected="selected"</#if>>乍得</option>
    <option status="1" value="34" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 34>selected="selected"</#if>>智利</option>
    <option status="1" value="35" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 35>selected="selected"</#if>>中国</option>
    <option status="1" value="36" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 36>selected="selected"</#if>>哥伦比亚</option>
    <option status="1" value="37" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 37>selected="selected"</#if>>刚果</option>
    <option status="1" value="38" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 38>selected="selected"</#if>>库克群岛</option>
    <option status="1" value="39" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 39>selected="selected"</#if>>哥斯达黎加</option>
    <option status="1" value="40" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 40>selected="selected"</#if>>古巴</option>
    <option status="1" value="41" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 41>selected="selected"</#if>>塞浦路斯</option>
    <option status="1" value="42" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 42>selected="selected"</#if>>捷克</option>
    <option status="1" value="43" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 43>selected="selected"</#if>>捷克</option>
    <option status="1" value="44" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 44>selected="selected"</#if>>丹麦</option>
    <option status="1" value="45" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 45>selected="selected"</#if>>吉布提</option>
    <option status="1" value="46" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 46>selected="selected"</#if>>多米尼加共和国</option>
    <option status="1" value="47" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 47>selected="selected"</#if>>厄瓜多尔</option>
    <option status="1" value="48" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 48>selected="selected"</#if>>埃及</option>
    <option status="1" value="49" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 49>selected="selected"</#if>>萨尔瓦多</option>
    <option status="1" value="50" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 50>selected="selected"</#if>>爱沙尼亚</option>
    <option status="1" value="51" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 51>selected="selected"</#if>>埃塞俄比亚</option>
    <option status="1" value="52" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 52>selected="selected"</#if>>斐济</option>
    <option status="1" value="53" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 53>selected="selected"</#if>>芬兰</option>
    <option status="1" value="54" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 54>selected="selected"</#if>>法国</option>
    <option status="1" value="55" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 55>selected="selected"</#if>>法属圭亚那</option>
    <option status="1" value="56" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 56>selected="selected"</#if>>法属玻利尼西亚</option>
    <option status="1" value="57" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 57>selected="selected"</#if>>加蓬</option>
    <option status="1" value="58" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 58>selected="selected"</#if>>冈比亚</option>
    <option status="1" value="59" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 59>selected="selected"</#if>>格鲁吉亚</option>
    <option status="1" value="60" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 60>selected="selected"</#if>>德国</option>
    <option status="1" value="61" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 61>selected="selected"</#if>>加纳</option>
    <option status="1" value="62" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 62>selected="selected"</#if>>直布罗陀</option>
    <option status="1" value="63" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 63>selected="selected"</#if>>希腊</option>
    <option status="1" value="64" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 64>selected="selected"</#if>>格林纳达</option>
    <option status="1" value="65" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 65>selected="selected"</#if>>关岛</option>
    <option status="1" value="66" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 66>selected="selected"</#if>>危地马拉</option>
    <option status="1" value="67" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 67>selected="selected"</#if>>几内亚</option>
    <option status="1" value="68" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 68>selected="selected"</#if>>圭亚那</option>
    <option status="1" value="69" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 69>selected="selected"</#if>>海地</option>
    <option status="1" value="70" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 70>selected="selected"</#if>>洪都拉斯</option>
    <option status="1" value="71" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 71>selected="selected"</#if>>香港特别行政区</option>
    <option status="1" value="72" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 72>selected="selected"</#if>>匈牙利</option>
    <option status="1" value="73" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 73>selected="selected"</#if>>冰岛</option>
    <option status="1" value="74" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 74>selected="selected"</#if>>印度</option>
    <option status="1" value="75" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 75>selected="selected"</#if>>印度尼西亚</option>
    <option status="1" value="76" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 76>selected="selected"</#if>>伊朗</option>
    <option status="1" value="77" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 77>selected="selected"</#if>>伊拉克</option>
    <option status="1" value="78" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 78>selected="selected"</#if>>爱尔兰</option>
    <option status="1" value="79" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 79>selected="selected"</#if>>以色列</option>
    <option status="1" value="80" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 80>selected="selected"</#if>>意大利</option>
    <option status="1" value="81" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 81>selected="selected"</#if>>牙买加</option>
    <option status="1" value="82" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 82>selected="selected"</#if>>日本</option>
    <option status="1" value="83" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 83>selected="selected"</#if>>约旦</option>
    <option status="1" value="84" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 84>selected="selected"</#if>>柬埔寨</option>
    <option status="1" value="85" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 85>selected="selected"</#if>>哈萨克斯坦</option>
    <option status="1" value="86" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 86>selected="selected"</#if>>肯尼亚</option>
    <option status="1" value="87" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 87>selected="selected"</#if>>韩国</option>
    <option status="1" value="88" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 88>selected="selected"</#if>>科威特</option>
    <option status="1" value="89" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 89>selected="selected"</#if>>吉尔吉斯坦</option>
    <option status="1" value="90" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 90>selected="selected"</#if>>老挝</option>
    <option status="1" value="91" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 91>selected="selected"</#if>>拉脱维亚</option>
    <option status="1" value="92" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 92>selected="selected"</#if>>黎巴嫩</option>
    <option status="1" value="93" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 93>selected="selected"</#if>>莱索托</option>
    <option status="1" value="94" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 94>selected="selected"</#if>>利比里亚</option>
    <option status="1" value="95" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 95>selected="selected"</#if>>利比亚</option>
    <option status="1" value="96" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 96>selected="selected"</#if>>列支敦士登</option>
    <option status="1" value="97" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 97>selected="selected"</#if>>立陶宛</option>
    <option status="1" value="98" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 98>selected="selected"</#if>>卢森堡</option>
    <option status="1" value="99" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 99>selected="selected"</#if>>澳门</option>
    <option status="1" value="100" <#if queryConditionMap?? && queryConditionMap.get('querycountry') ==100>selected="selected"</#if>>马达加斯加</option>
    <option status="1" value="101" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 101>selected="selected"</#if>>马拉维</option>
    <option status="1" value="102" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 102>selected="selected"</#if>>马来西亚</option>
    <option status="1" value="103" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 103>selected="selected"</#if>>马尔代夫</option>
    <option status="1" value="104" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 104>selected="selected"</#if>>马里</option>
    <option status="1" value="105" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 105>selected="selected"</#if>>马耳他</option>
    <option status="1" value="106" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 106>selected="selected"</#if>>毛里求斯</option>
    <option status="1" value="107" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 107>selected="selected"</#if>>墨西哥</option>
    <option status="1" value="108" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 108>selected="selected"</#if>>摩尔多瓦</option>
    <option status="1" value="109" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 109>selected="selected"</#if>>摩纳哥</option>
    <option status="1" value="110" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 110>selected="selected"</#if>>蒙古</option>
    <option status="1" value="111" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 111>selected="selected"</#if>>蒙特塞拉特岛</option>
    <option status="1" value="112" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 112>selected="selected"</#if>>摩洛哥</option>
    <option status="1" value="113" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 113>selected="selected"</#if>>莫桑比克</option>
    <option status="1" value="114" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 114>selected="selected"</#if>>纳米比亚</option>
    <option status="1" value="115" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 115>selected="selected"</#if>>瑙鲁</option>
    <option status="1" value="116" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 116>selected="selected"</#if>>尼泊尔</option>
    <option status="1" value="117" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 117>selected="selected"</#if>>荷兰</option>
    <option status="1" value="118" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 118>selected="selected"</#if>>新西兰</option>
    <option status="1" value="119" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 119>selected="selected"</#if>>尼加拉瓜</option>
    <option status="1" value="120" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 120>selected="selected"</#if>>尼日尔</option>
    <option status="1" value="121" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 121>selected="selected"</#if>>尼日利亚</option>
    <option status="1" value="122" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 122>selected="selected"</#if>>朝鲜</option>
    <option status="1" value="123" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 123>selected="selected"</#if>>挪威</option>
    <option status="1" value="124" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 124>selected="selected"</#if>>阿曼</option>
    <option status="1" value="125" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 125>selected="selected"</#if>>巴基斯坦</option>
    <option status="1" value="126" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 126>selected="selected"</#if>>巴勒斯坦</option>
    <option status="1" value="127" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 127>selected="selected"</#if>>巴拿马</option>
    <option status="1" value="128" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 128>selected="selected"</#if>>巴布亚新几内亚</option>
    <option status="1" value="129" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 129>selected="selected"</#if>>巴拉圭</option>
    <option status="1" value="130" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 130>selected="selected"</#if>>秘鲁</option>
    <option status="1" value="131" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 131>selected="selected"</#if>>菲律宾</option>
    <option status="1" value="132" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 132>selected="selected"</#if>>波兰</option>
    <option status="1" value="133" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 133>selected="selected"</#if>>葡萄牙</option>
    <option status="1" value="134" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 134>selected="selected"</#if>>波多黎各</option>
    <option status="1" value="135" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 135>selected="selected"</#if>>卡塔尔</option>
    <option status="1" value="136" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 136>selected="selected"</#if>>科特迪瓦共和国</option>
    <option status="1" value="137" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 137>selected="selected"</#if>>罗马尼亚</option>
    <option status="1" value="138" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 138>selected="selected"</#if>>俄罗斯</option>
    <option status="1" value="139" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 139>selected="selected"</#if>>圣文森特岛</option>
    <option status="1" value="140" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 140>selected="selected"</#if>>圣马力诺</option>
    <option status="1" value="141" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 141>selected="selected"</#if>>圣多美和普林西比</option>
    <option status="1" value="142" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 142>selected="selected"</#if>>沙特阿拉伯</option>
    <option status="1" value="143" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 143>selected="selected"</#if>>塞内加尔</option>
    <option status="1" value="144" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 144>selected="selected"</#if>>塞舌尔</option>
    <option status="1" value="145" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 145>selected="selected"</#if>>塞拉利昂</option>
    <option status="1" value="146" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 146>selected="selected"</#if>>新加坡</option>
    <option status="1" value="147" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 147>selected="selected"</#if>>斯洛伐克</option>
    <option status="1" value="148" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 148>selected="selected"</#if>>斯洛文尼亚</option>
    <option status="1" value="149" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 149>selected="selected"</#if>>所罗门群岛</option>
    <option status="1" value="150" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 150>selected="selected"</#if>>索马里</option>
    <option status="1" value="151" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 151>selected="selected"</#if>>南非</option>
    <option status="1" value="152" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 152>selected="selected"</#if>>西班牙</option>
    <option status="1" value="153" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 153>selected="selected"</#if>>斯里兰卡</option>
    <option status="1" value="154" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 154>selected="selected"</#if>>圣卢西亚</option>
    <option status="1" value="155" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 155>selected="selected"</#if>>苏丹</option>
    <option status="1" value="156" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 156>selected="selected"</#if>>苏里南</option>
    <option status="1" value="157" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 157>selected="selected"</#if>>斯威士兰</option>
    <option status="1" value="158" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 158>selected="selected"</#if>>瑞典</option>
    <option status="1" value="159" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 159>selected="selected"</#if>>瑞士</option>
    <option status="1" value="160" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 160>selected="selected"</#if>>叙利亚</option>
    <option status="1" value="161" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 161>selected="selected"</#if>>台湾省</option>
    <option status="1" value="162" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 162>selected="selected"</#if>>塔吉克斯坦</option>
    <option status="1" value="163" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 163>selected="selected"</#if>>坦桑尼亚</option>
    <option status="1" value="164" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 164>selected="selected"</#if>>泰国</option>
    <option status="1" value="165" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 165>selected="selected"</#if>>多哥</option>
    <option status="1" value="166" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 166>selected="selected"</#if>>汤加</option>
    <option status="1" value="167" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 167>selected="selected"</#if>>特立尼达和多巴哥</option>
    <option status="1" value="168" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 168>selected="selected"</#if>>突尼斯</option>
    <option status="1" value="169" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 169>selected="selected"</#if>>土耳其</option>
    <option status="1" value="170" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 170>selected="selected"</#if>>土库曼斯坦</option>
    <option status="1" value="171" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 171>selected="selected"</#if>>乌干达</option>
    <option status="1" value="172" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 172>selected="selected"</#if>>乌克兰</option>
    <option status="1" value="173" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 173>selected="selected"</#if>>阿拉伯联合酋长国</option>
    <option status="1" value="174" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 174>selected="selected"</#if>>英国</option>
    <option status="1" value="175" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 175>selected="selected"</#if>>美国</option>
    <option status="1" value="176" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 176>selected="selected"</#if>>乌拉圭</option>
    <option status="1" value="177" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 177>selected="selected"</#if>>乌兹别克斯坦</option>
    <option status="1" value="178" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 178>selected="selected"</#if>>委内瑞拉</option>
    <option status="1" value="179" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 179>selected="selected"</#if>>越南</option>
    <option status="1" value="180" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 180>selected="selected"</#if>>也门</option>
    <option status="1" value="181" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 181>selected="selected"</#if>>南斯拉夫</option>
    <option status="1" value="182" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 182>selected="selected"</#if>>扎伊尔</option>
    <option status="1" value="183" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 183>selected="selected"</#if>>赞比亚</option>
    <option status="1" value="184" <#if queryConditionMap?? && queryConditionMap.get('querycountry') == 184>selected="selected"</#if>>津巴布韦</option>